/**
 * NASHTY OS - WhatsApp Export Module
 * Export reports ke WhatsApp dengan template
 * Date: June 23, 2026
 */

class WhatsAppExporter {
  constructor() {
    this.templates = {
      daily: this.getDailyTemplate(),
      weekly: this.getWeeklyTemplate(),
      monthly: this.getMonthlyTemplate(),
      custom: this.getCustomTemplate()
    };
  }

  /**
   * Generate WhatsApp message from report data
   */
  generateMessage(reportData, templateType = 'daily') {
    const template = this.templates[templateType] || this.templates.daily;
    return template(reportData);
  }

  /**
   * Daily Report Template
   */
  getDailyTemplate() {
    return (data) => {
      const date = new Date(data.date).toLocaleDateString('id-ID', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });

      return `
🍽️ *NASHTY RESTAURANT*
📊 *Laporan Harian*

📅 *Tanggal:* ${date}
🏢 *Outlet:* ${data.outletName}

━━━━━━━━━━━━━━━━━━━━
💰 *RINGKASAN PENJUALAN*
━━━━━━━━━━━━━━━━━━━━

*Gross Sales:* Rp ${this.formatCurrency(data.grossSales)}
*Diskon:* -Rp ${this.formatCurrency(data.totalDiscount)}
*Pajak:* Rp ${this.formatCurrency(data.totalTax)}
*Net Sales:* Rp ${this.formatCurrency(data.netSales)}

━━━━━━━━━━━━━━━━━━━━
📦 *DETAIL TRANSAKSI*
━━━━━━━━━━━━━━━━━━━━

*Total Transaksi:* ${data.totalOrders} orders
*Average Order:* Rp ${this.formatCurrency(data.avgOrderValue)}

*Payment Methods:*
💵 Cash: Rp ${this.formatCurrency(data.payments.cash || 0)}
💳 Debit: Rp ${this.formatCurrency(data.payments.debit || 0)}
🏦 Transfer: Rp ${this.formatCurrency(data.payments.transfer || 0)}
🚗 Gojek: Rp ${this.formatCurrency(data.payments.gojek || 0)}
🛒 Shopee: Rp ${this.formatCurrency(data.payments.shopee || 0)}

*Order Types:*
🍽️ Dine-In: ${data.orderTypes.dineIn || 0} orders
📦 Takeaway: ${data.orderTypes.takeaway || 0} orders
🚚 Delivery: ${data.orderTypes.delivery || 0} orders

━━━━━━━━━━━━━━━━━━━━
🔥 *TOP 5 PRODUK*
━━━━━━━━━━━━━━━━━━━━

${this.formatTopProducts(data.topProducts)}

━━━━━━━━━━━━━━━━━━━━
👥 *STAFF PERFORMANCE*
━━━━━━━━━━━━━━━━━━━━

${this.formatStaffPerformance(data.staffPerformance)}

━━━━━━━━━━━━━━━━━━━━

_Generated by NASHTY OS_
_${new Date().toLocaleString('id-ID')}_
      `.trim();
    };
  }

  /**
   * Weekly Report Template
   */
  getWeeklyTemplate() {
    return (data) => {
      const startDate = new Date(data.startDate).toLocaleDateString('id-ID', {
        day: 'numeric',
        month: 'short'
      });
      const endDate = new Date(data.endDate).toLocaleDateString('id-ID', {
        day: 'numeric',
        month: 'short',
        year: 'numeric'
      });

      return `
🍽️ *NASHTY RESTAURANT*
📊 *Laporan Mingguan*

📅 *Periode:* ${startDate} - ${endDate}
🏢 *Outlet:* ${data.outletName}

━━━━━━━━━━━━━━━━━━━━
💰 *RINGKASAN PENJUALAN*
━━━━━━━━━━━━━━━━━━━━

*Total Gross Sales:* Rp ${this.formatCurrency(data.grossSales)}
*Total Net Sales:* Rp ${this.formatCurrency(data.netSales)}
*Total Transaksi:* ${data.totalOrders} orders
*Rata-rata/Hari:* Rp ${this.formatCurrency(data.avgPerDay)}

━━━━━━━━━━━━━━━━━━━━
📈 *TREND HARIAN*
━━━━━━━━━━━━━━━━━━━━

${this.formatDailyTrend(data.dailyBreakdown)}

━━━━━━━━━━━━━━━━━━━━
💳 *PAYMENT CHANNELS*
━━━━━━━━━━━━━━━━━━━━

💵 Cash: Rp ${this.formatCurrency(data.payments.cash || 0)}
💳 Debit: Rp ${this.formatCurrency(data.payments.debit || 0)}
🏦 Transfer: Rp ${this.formatCurrency(data.payments.transfer || 0)}
🚗 *Gojek:* Rp ${this.formatCurrency(data.payments.gojek || 0)}
🛒 *Shopee:* Rp ${this.formatCurrency(data.payments.shopee || 0)}

━━━━━━━━━━━━━━━━━━━━
🔥 *TOP 10 PRODUK MINGGU INI*
━━━━━━━━━━━━━━━━━━━━

${this.formatTopProducts(data.topProducts, 10)}

━━━━━━━━━━━━━━━━━━━━

_Generated by NASHTY OS_
_${new Date().toLocaleString('id-ID')}_
      `.trim();
    };
  }

  /**
   * Monthly Report Template
   */
  getMonthlyTemplate() {
    return (data) => {
      const month = new Date(data.month).toLocaleDateString('id-ID', {
        month: 'long',
        year: 'numeric'
      });

      return `
🍽️ *NASHTY RESTAURANT*
📊 *Laporan Bulanan*

📅 *Bulan:* ${month}
🏢 *Outlet:* ${data.outletName}

━━━━━━━━━━━━━━━━━━━━
💰 *TOTAL PENJUALAN*
━━━━━━━━━━━━━━━━━━━━

*Gross Sales:* Rp ${this.formatCurrency(data.grossSales)}
*Net Sales:* Rp ${this.formatCurrency(data.netSales)}
*Total Transaksi:* ${data.totalOrders} orders

*Pertumbuhan:*
📈 vs Bulan Lalu: ${data.growth >= 0 ? '+' : ''}${data.growth}%

━━━━━━━━━━━━━━━━━━━━
📅 *BREAKDOWN MINGGUAN*
━━━━━━━━━━━━━━━━━━━━

${this.formatWeeklyBreakdown(data.weeklyBreakdown)}

━━━━━━━━━━━━━━━━━━━━
💳 *PAYMENT CHANNELS*
━━━━━━━━━━━━━━━━━━━━

💵 Cash: Rp ${this.formatCurrency(data.payments.cash || 0)} (${this.getPercentage(data.payments.cash, data.grossSales)})
💳 Debit: Rp ${this.formatCurrency(data.payments.debit || 0)} (${this.getPercentage(data.payments.debit, data.grossSales)})
🏦 Transfer: Rp ${this.formatCurrency(data.payments.transfer || 0)} (${this.getPercentage(data.payments.transfer, data.grossSales)})
🚗 *Gojek:* Rp ${this.formatCurrency(data.payments.gojek || 0)} (${this.getPercentage(data.payments.gojek, data.grossSales)})
🛒 *Shopee:* Rp ${this.formatCurrency(data.payments.shopee || 0)} (${this.getPercentage(data.payments.shopee, data.grossSales)})

━━━━━━━━━━━━━━━━━━━━
🏆 *TOP PERFORMERS*
━━━━━━━━━━━━━━━━━━━━

${this.formatTopProducts(data.topProducts, 10)}

━━━━━━━━━━━━━━━━━━━━

_Generated by NASHTY OS_
_${new Date().toLocaleString('id-ID')}_
      `.trim();
    };
  }

  /**
   * Custom Report Template
   */
  getCustomTemplate() {
    return (data) => {
      return `
🍽️ *NASHTY RESTAURANT*
📊 *Laporan Custom*

📅 *Periode:* ${data.startDate} - ${data.endDate}
🏢 *Outlet:* ${data.outletName}

━━━━━━━━━━━━━━━━━━━━
💰 *RINGKASAN*
━━━━━━━━━━━━━━━━━━━━

*Gross Sales:* Rp ${this.formatCurrency(data.grossSales)}
*Net Sales:* Rp ${this.formatCurrency(data.netSales)}
*Total Orders:* ${data.totalOrders}

💳 *Gojek:* Rp ${this.formatCurrency(data.payments.gojek || 0)}
🛒 *Shopee:* Rp ${this.formatCurrency(data.payments.shopee || 0)}

━━━━━━━━━━━━━━━━━━━━

_Generated by NASHTY OS_
      `.trim();
    };
  }

  /**
   * Helper: Format currency
   */
  formatCurrency(amount) {
    return new Intl.NumberFormat('id-ID').format(amount || 0);
  }

  /**
   * Helper: Get percentage
   */
  getPercentage(part, total) {
    if (!total || total === 0) return '0%';
    return ((part / total) * 100).toFixed(1) + '%';
  }

  /**
   * Helper: Format top products
   */
  formatTopProducts(products, limit = 5) {
    if (!products || products.length === 0) {
      return '_(Belum ada data produk)_';
    }

    return products
      .slice(0, limit)
      .map((p, i) => {
        const medal = i === 0 ? '🥇' : i === 1 ? '🥈' : i === 2 ? '🥉' : `${i + 1}.`;
        return `${medal} ${p.name}: ${p.quantity} terjual (Rp ${this.formatCurrency(p.total)})`;
      })
      .join('\n');
  }

  /**
   * Helper: Format staff performance
   */
  formatStaffPerformance(staff) {
    if (!staff || staff.length === 0) {
      return '_(Belum ada data staff)_';
    }

    return staff
      .slice(0, 5)
      .map((s, i) => {
        return `${i + 1}. ${s.name}: ${s.orders} orders (Rp ${this.formatCurrency(s.total)})`;
      })
      .join('\n');
  }

  /**
   * Helper: Format daily trend
   */
  formatDailyTrend(dailyData) {
    if (!dailyData || dailyData.length === 0) {
      return '_(Belum ada data harian)_';
    }

    return dailyData
      .map((day) => {
        const date = new Date(day.date).toLocaleDateString('id-ID', {
          weekday: 'short',
          day: 'numeric',
          month: 'short'
        });
        return `${date}: Rp ${this.formatCurrency(day.sales)} (${day.orders} orders)`;
      })
      .join('\n');
  }

  /**
   * Helper: Format weekly breakdown
   */
  formatWeeklyBreakdown(weeklyData) {
    if (!weeklyData || weeklyData.length === 0) {
      return '_(Belum ada data mingguan)_';
    }

    return weeklyData
      .map((week, i) => {
        return `Minggu ${i + 1}: Rp ${this.formatCurrency(week.sales)} (${week.orders} orders)`;
      })
      .join('\n');
  }

  /**
   * Send to WhatsApp (opens WhatsApp with pre-filled message)
   */
  sendToWhatsApp(message, phoneNumber = '') {
    // URL encode the message
    const encodedMessage = encodeURIComponent(message);
    
    // Format phone number (remove +, spaces, dashes)
    const cleanPhone = phoneNumber.replace(/[\s\-\+]/g, '');
    
    // WhatsApp URL
    let url;
    if (cleanPhone) {
      // Send to specific number
      url = `https://wa.me/${cleanPhone}?text=${encodedMessage}`;
    } else {
      // Open WhatsApp with message (user chooses recipient)
      url = `https://api.whatsapp.com/send?text=${encodedMessage}`;
    }
    
    // Open in new window
    window.open(url, '_blank');
  }

  /**
   * Copy message to clipboard
   */
  async copyToClipboard(message) {
    try {
      await navigator.clipboard.writeText(message);
      return true;
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
      
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = message;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.select();
      
      try {
        document.execCommand('copy');
        document.body.removeChild(textArea);
        return true;
      } catch (err) {
        document.body.removeChild(textArea);
        return false;
      }
    }
  }

  /**
   * Export as text file
   */
  downloadAsText(message, filename = 'laporan.txt') {
    const blob = new Blob([message], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  }

  /**
   * Preview message (modal)
   */
  showPreview(message, title = 'Preview Laporan') {
    const modal = document.createElement('div');
    modal.className = 'whatsapp-preview-modal';
    modal.innerHTML = `
      <div class="modal-overlay" onclick="this.parentElement.remove()"></div>
      <div class="modal-content">
        <div class="modal-header">
          <h3>${title}</h3>
          <button class="close-btn" onclick="this.closest('.whatsapp-preview-modal').remove()">×</button>
        </div>
        <div class="modal-body">
          <div class="preview-box">${this.convertToHTML(message)}</div>
        </div>
        <div class="modal-footer">
          <button class="btn-secondary" onclick="WhatsAppExporter.instance.copyToClipboard(\`${message.replace(/`/g, '\\`')}\`)">
            📋 Copy
          </button>
          <button class="btn-secondary" onclick="WhatsAppExporter.instance.downloadAsText(\`${message.replace(/`/g, '\\`')}\`)">
            💾 Download
          </button>
          <button class="btn-primary" onclick="WhatsAppExporter.instance.sendToWhatsApp(\`${message.replace(/`/g, '\\`')}\`)">
            📱 Send WhatsApp
          </button>
        </div>
      </div>
    `;
    
    document.body.appendChild(modal);
  }

  /**
   * Convert WhatsApp format to HTML
   */
  convertToHTML(message) {
    return message
      .replace(/\*([^*]+)\*/g, '<strong>$1</strong>') // Bold
      .replace(/_([^_]+)_/g, '<em>$1</em>') // Italic
      .replace(/~([^~]+)~/g, '<del>$1</del>') // Strikethrough
      .replace(/\n/g, '<br>'); // Line breaks
  }
}

// Create global instance
WhatsAppExporter.instance = new WhatsAppExporter();

// Export
if (typeof module !== 'undefined' && module.exports) {
  module.exports = WhatsAppExporter;
} else {
  window.WhatsAppExporter = WhatsAppExporter;
}

console.log('✅ WhatsAppExporter loaded');
